Repository openhealthcare/opal, pull requests merged in 2018-12, with the labels that each got.

#1655 dummy_options_module.py from the plugin scaffold hasn't been required…
  opal/scaffolding/plugin_scaffold/app/tests/dummy_options_module.py
Labels: Code Review

#1659 change so that we will always resolve edit item with a promise that w…
  changelog.md
  opal/static/js/opal/controllers/edit_item.js
  opal/static/js/opal/services/record_editor.js
  opal/static/js/test/edit_item.controller.test.js
  opal/static/js/test/record_editor_test.js
Labels: in progress

#1641 Django2
  .travis.yml
  changelog.md
  doc/docs/reference/upgrading.md
  opal/core/application.py
  opal/core/fields.py
  opal/core/log.py
  opal/core/pathway/pathways.py
  opal/core/pathway/tests/test_api.py
  opal/core/pathway/tests/test_pathways.py
  opal/core/pathway/tests/test_steps.py
  opal/core/pathway/tests/test_template_tags.py
  opal/core/pathway/tests/test_url.py
  opal/core/pathway/tests/test_views.py
  opal/core/patient_lists.py
  opal/core/search/extract.py
  opal/core/search/tests/test_api.py
  opal/core/search/tests/test_extract.py
  opal/core/search/views.py
  opal/middleware.py
  opal/migrations/0001_initial.py
  opal/migrations/0003_auto_20150922_1825.py
  opal/migrations/0009_glossolaliasubscription.py
  opal/migrations/0011_patientrecordaccess.py
  opal/migrations/0013_inpatientadmission.py
  opal/migrations/0037_auto_20181114_1445.py
  opal/models.py
  opal/tests/migrations/0001_initial.py
  opal/tests/migrations/0002_auto_20181102_1642.py
  opal/tests/migrations/0003_datingmodel_gettermodel_serialisablemodel_updatablemodelinstance.py
  opal/tests/migrations/__init__.py
  opal/tests/models.py
  opal/tests/test_api.py
  opal/tests/test_core_fields.py
  opal/tests/test_episode.py
  opal/tests/test_models.py
  opal/tests/test_models_mixins.py
  opal/tests/test_patient.py
  opal/tests/test_patient_lists.py
  opal/tests/test_templatetags_forms.py
  opal/tests/test_urls.py
  opal/tests/test_utils_fields.py
  opal/tests/test_views.py
  opal/urls.py
  opal/views.py
  runtests.py
  setup.py
Labels: Code Review, blocked
